### PR TITLE
fix: IssuePageHeader displaying org instead of repo

### PR DESCRIPTION
**Pull request by bravo-kernel**
Awesome stuff, learning a lot. I noticed an error while testing the advanced tutorial, this fixes it.

### CODE REVIEW

**Comment by markerikson** [comment]
Glad you liked it!

And thanks, good catch.

I'll leave this open for the moment and see whether I want to re-create the relevant commits, or just merge this PR.

**Comment by bravo-kernel** [comment]
You're welcome and sure, I hesitated to even PR to prevent stuff from breaking. Anyway, on with the tut 💃

**Comment by markerikson** [comment]
Fixed in a history rewrite.  Thanks!

**Comment by bravo-kernel** [comment]
Ty 👍🏼👍🏼

**Pull request closed without merging**
